/* Undefs */
#undef MOUSEKEY_DELAY 
#undef MOUSEKEY_INTERVAL

/* Mouse Keys - Kinetic Mode */
#define MK_KINETIC_SPEED
#define MOUSEKEY_DELAY 8
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_INITIAL_SPEED 35
#define MOUSEKEY_BASE_SPEED 50
#define MOUSEKEY_DECELERATED_SPEED 45
#define MOUSEKEY_ACCELERATED_SPEED 175